package com.fleet.trucker.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.fleet.trucker.entity.Alert;
import com.fleet.trucker.service.AlertService;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

@RestController
@RequestMapping(path = "alerts")
@Api(value="Alerts generated by the Rules Engine for Readings")
public class AlertController {
	
	@Autowired
	private AlertService service;

	@RequestMapping(method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
	@ApiOperation(value="Retrieve all the historical Alerts", response=List.class)
	public List<Alert> findAll() {
		return service.findAll();
	}

	@RequestMapping(method = RequestMethod.GET, path = "/{id}", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
	@ApiOperation(value="Retrieve Alerts with ID", response=Alert.class)
	public Alert findById(@PathVariable("id") String id) {
		return service.findById(id);
	}

	@RequestMapping(method = RequestMethod.GET, path = "/vin/{vin}", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
	@ApiOperation(value="Retrieve all the historical Alerts for Vehicle with VIN", response=List.class)
	public List<Alert> findAllByVin(@PathVariable("vin") String vin) {
		return service.findAllByVin(vin);
	}

	@RequestMapping(method = RequestMethod.GET, path = "/readingType/{readingType}", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
	@ApiOperation(value="Retrieve all the historical Alerts with given Reading Type", response=List.class)
	public List<Alert> findAllByReadingType(@PathVariable("readingType") String readingType) {
		return service.findAllByReadingType(readingType);
	}

	@RequestMapping(method = RequestMethod.GET, path = "/priority/{priority}", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
	@ApiOperation(value="Retrieve all the historical Alerts with given Priority", response=List.class)
	public List<Alert> findAllByPriority(@PathVariable("priority") String priority) {
		return service.findAllByPriority(priority);
	}

	@RequestMapping(method = RequestMethod.GET, path = "/timestamp/{priority}", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
	@ApiOperation(value="Retrieve all Alerts in last 2 hours with given Priority", response=List.class)
	public List<Alert> findAllByTimestamp(@PathVariable("priority") int priority) {
		return service.findAllByPriorityAndTimestamp(priority);
	}
	
	@RequestMapping(method = RequestMethod.GET, path = "/sortvehalerts", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
	@ApiOperation(value="Retrieve sorted list of Alerts based on Priority", response=List.class)
	public List<Alert> sortAllVehByAlert() {
		return service.sortAllVehByAlert();
	}

}
